// Every country flag derived from its ISO 3166-1 alpha-2 code via regional
// indicator symbols — no image assets needed.
export function flagOf(code) {
  if (!code || code.length !== 2) return "";
  const A = 0x1f1e6;
  const a = "A".charCodeAt(0);
  return String.fromCodePoint(A + code.charCodeAt(0) - a, A + code.charCodeAt(1) - a);
}

// Country → suggested display currency (must exist in CURRENCIES, else null).
// Falls back to detectCurrencyFromLocation for anything not listed.
export const COUNTRIES = [
  { name: "Afghanistan", code: "AF" },
  { name: "Albania", code: "AL", currency: "EUR" },
  { name: "Algeria", code: "DZ" },
  { name: "Andorra", code: "AD", currency: "EUR" },
  { name: "Angola", code: "AO" },
  { name: "Antigua and Barbuda", code: "AG", currency: "USD" },
  { name: "Argentina", code: "AR", currency: "USD" },
  { name: "Armenia", code: "AM" },
  { name: "Australia", code: "AU", currency: "USD" },
  { name: "Austria", code: "AT", currency: "EUR" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS", currency: "USD" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB", currency: "USD" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE", currency: "EUR" },
  { name: "Belize", code: "BZ", currency: "USD" },
  { name: "Benin", code: "BJ" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO", currency: "USD" },
  { name: "Bosnia and Herzegovina", code: "BA", currency: "EUR" },
  { name: "Botswana", code: "BW" },
  { name: "Brazil", code: "BR", currency: "USD" },
  { name: "Brunei", code: "BN", currency: "USD" },
  { name: "Bulgaria", code: "BG", currency: "EUR" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodia", code: "KH", currency: "USD" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA", currency: "USD" },
  { name: "Cape Verde", code: "CV", currency: "EUR" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL", currency: "USD" },
  { name: "China", code: "CN", currency: "USD" },
  { name: "Colombia", code: "CO", currency: "USD" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Congo (DRC)", code: "CD" },
  { name: "Costa Rica", code: "CR", currency: "USD" },
  { name: "Croatia", code: "HR", currency: "EUR" },
  { name: "Cuba", code: "CU", currency: "USD" },
  { name: "Cyprus", code: "CY", currency: "EUR" },
  { name: "Czech Republic", code: "CZ", currency: "EUR" },
  { name: "Denmark", code: "DK", currency: "EUR" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM", currency: "USD" },
  { name: "Dominican Republic", code: "DO", currency: "USD" },
  { name: "Ecuador", code: "EC", currency: "USD" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV", currency: "USD" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE", currency: "EUR" },
  { name: "Eswatini", code: "SZ" },
  { name: "Ethiopia", code: "ET" },
  { name: "Fiji", code: "FJ", currency: "USD" },
  { name: "Finland", code: "FI", currency: "EUR" },
  { name: "France", code: "FR", currency: "EUR" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE", currency: "EUR" },
  { name: "Ghana", code: "GH" },
  { name: "Greece", code: "GR", currency: "EUR" },
  { name: "Grenada", code: "GD", currency: "USD" },
  { name: "Guatemala", code: "GT", currency: "USD" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY", currency: "USD" },
  { name: "Haiti", code: "HT", currency: "USD" },
  { name: "Honduras", code: "HN", currency: "USD" },
  { name: "Hong Kong", code: "HK", currency: "USD" },
  { name: "Hungary", code: "HU", currency: "EUR" },
  { name: "Iceland", code: "IS", currency: "EUR" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE", currency: "EUR" },
  { name: "Israel", code: "IL", currency: "USD" },
  { name: "Italy", code: "IT", currency: "EUR" },
  { name: "Ivory Coast", code: "CI" },
  { name: "Jamaica", code: "JM", currency: "USD" },
  { name: "Japan", code: "JP", currency: "USD" },
  { name: "Jordan", code: "JO", currency: "USD" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI", currency: "USD" },
  { name: "Kuwait", code: "KW", currency: "USD" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Laos", code: "LA" },
  { name: "Latvia", code: "LV", currency: "EUR" },
  { name: "Lebanon", code: "LB", currency: "USD" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR", currency: "USD" },
  { name: "Libya", code: "LY" },
  { name: "Liechtenstein", code: "LI", currency: "EUR" },
  { name: "Lithuania", code: "LT", currency: "EUR" },
  { name: "Luxembourg", code: "LU", currency: "EUR" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY", currency: "USD" },
  { name: "Maldives", code: "MV", currency: "USD" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT", currency: "EUR" },
  { name: "Marshall Islands", code: "MH", currency: "USD" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU", currency: "USD" },
  { name: "Mexico", code: "MX", currency: "USD" },
  { name: "Micronesia", code: "FM", currency: "USD" },
  { name: "Moldova", code: "MD", currency: "EUR" },
  { name: "Monaco", code: "MC", currency: "EUR" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME", currency: "EUR" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR", currency: "USD" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL", currency: "EUR" },
  { name: "New Zealand", code: "NZ", currency: "USD" },
  { name: "Nicaragua", code: "NI", currency: "USD" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG", currency: "NGN" },
  { name: "North Korea", code: "KP" },
  { name: "North Macedonia", code: "MK", currency: "EUR" },
  { name: "Norway", code: "NO", currency: "EUR" },
  { name: "Oman", code: "OM", currency: "USD" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW", currency: "USD" },
  { name: "Palestine", code: "PS" },
  { name: "Panama", code: "PA", currency: "USD" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY", currency: "USD" },
  { name: "Peru", code: "PE", currency: "USD" },
  { name: "Philippines", code: "PH", currency: "USD" },
  { name: "Poland", code: "PL", currency: "EUR" },
  { name: "Portugal", code: "PT", currency: "EUR" },
  { name: "Qatar", code: "QA", currency: "USD" },
  { name: "Romania", code: "RO", currency: "EUR" },
  { name: "Russia", code: "RU" },
  { name: "Rwanda", code: "RW" },
  { name: "Saint Kitts and Nevis", code: "KN", currency: "USD" },
  { name: "Saint Lucia", code: "LC", currency: "USD" },
  { name: "Saint Vincent and the Grenadines", code: "VC", currency: "USD" },
  { name: "Samoa", code: "WS", currency: "USD" },
  { name: "San Marino", code: "SM", currency: "EUR" },
  { name: "Sao Tome and Principe", code: "ST", currency: "EUR" },
  { name: "Saudi Arabia", code: "SA", currency: "USD" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS", currency: "EUR" },
  { name: "Seychelles", code: "SC", currency: "USD" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG", currency: "USD" },
  { name: "Slovakia", code: "SK", currency: "EUR" },
  { name: "Slovenia", code: "SI", currency: "EUR" },
  { name: "Solomon Islands", code: "SB", currency: "USD" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Korea", code: "KR", currency: "USD" },
  { name: "South Sudan", code: "SS" },
  { name: "Spain", code: "ES", currency: "EUR" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR", currency: "USD" },
  { name: "Sweden", code: "SE", currency: "EUR" },
  { name: "Switzerland", code: "CH", currency: "EUR" },
  { name: "Syria", code: "SY" },
  { name: "Taiwan", code: "TW", currency: "USD" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania", code: "TZ" },
  { name: "Thailand", code: "TH", currency: "USD" },
  { name: "Timor-Leste", code: "TL", currency: "USD" },
  { name: "Togo", code: "TG" },
  { name: "Tonga", code: "TO", currency: "USD" },
  { name: "Trinidad and Tobago", code: "TT", currency: "USD" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR", currency: "EUR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Tuvalu", code: "TV", currency: "USD" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA", currency: "EUR" },
  { name: "United Arab Emirates", code: "AE", currency: "USD" },
  { name: "United Kingdom", code: "GB", currency: "GBP" },
  { name: "United States", code: "US", currency: "USD" },
  { name: "Uruguay", code: "UY", currency: "USD" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU", currency: "USD" },
  { name: "Vatican City", code: "VA", currency: "EUR" },
  { name: "Venezuela", code: "VE", currency: "USD" },
  { name: "Vietnam", code: "VN", currency: "USD" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

export function findCountry(name) {
  if (!name) return null;
  const q = name.trim().toLowerCase();
  return COUNTRIES.find((c) => c.name.toLowerCase() === q) ?? null;
}

export function filterCountries(query, limit = 60) {
  if (!query) return COUNTRIES.slice(0, limit);
  const q = query.trim().toLowerCase();
  if (!q) return COUNTRIES.slice(0, limit);

  const starts = [];
  const contains = [];
  for (const c of COUNTRIES) {
    const name = c.name.toLowerCase();
    if (name.startsWith(q)) starts.push(c);
    else if (name.includes(q)) contains.push(c);
    if (starts.length + contains.length >= limit) break;
  }
  return [...starts, ...contains].slice(0, limit);
}
